server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rent_hub
    username: postgres
    password: postgres

jwtconfig:
  secret: secret
  expiration: 6000000

currency:
  client:
    url: "http://www.cbr.ru/scripts/XML_daily.asp"